// <auto-generated />
using System;
using ControleVeicular.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControleVeicular.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControleVeicular.Domain.Model.Advertisement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("BuyPrice");

                    b.Property<string>("Color");

                    b.Property<string>("DriveTrain");

                    b.Property<int?>("FabricationYear");

                    b.Property<string>("FuelType");

                    b.Property<int?>("ModelYear");

                    b.Property<DateTime?>("SellDate");

                    b.Property<float?>("SellPrice");

                    b.Property<string>("TransmissionType");

                    b.Property<Guid>("VehicleId");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("ControleVeicular.Domain.Model.AdvertisementPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AdvertisementId");

                    b.Property<string>("PhotoURL");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementId");

                    b.ToTable("AdvertisementPhotos");
                });

            modelBuilder.Entity("ControleVeicular.Domain.Model.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<string>("Pais");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("ControleVeicular.Domain.Model.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bodytype");

                    b.Property<Guid>("BrandId");

                    b.Property<int?>("EngineDisplacement");

                    b.Property<string>("EngineSpecification");

                    b.Property<string>("ModelName");

                    b.Property<string>("ModelSpecification");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("ControleVeicular.Domain.Model.Advertisement", b =>
                {
                    b.HasOne("ControleVeicular.Domain.Model.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ControleVeicular.Domain.Model.AdvertisementPhoto", b =>
                {
                    b.HasOne("ControleVeicular.Domain.Model.Advertisement", "Advertisement")
                        .WithMany("AdPhotos")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ControleVeicular.Domain.Model.Vehicle", b =>
                {
                    b.HasOne("ControleVeicular.Domain.Model.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
